Keymdall/dashboard/urls.py
from django.urls import path, include
from . import views

app_name = 'dashboard'

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("login", views.login_form, name="login"),
    path("register", views.register_form, name="register"),
    path("logout", views.logout_user, name="logout"),
    path("edit_pin", views.edit_pin, name="edit_pin"),
    path("set_pin", views.set_pin, name="set_pin"),
    path("change_masterpassword", views.change_masterpassword, name="change_masterpassword"),
    path("change_email", views.change_email, name="change_email"),
    path("delete_account", views.delete_account, name="delete_account"),


]

Keymdall/keymdall/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("vault.urls", namespace='vault')),
    path('dashboard/', include("dashboard.urls", namespace='dashboard')),

    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
]

Keymdall/vault/urls.py
from django.urls import path
from . import views

app_name = 'vault'

urlpatterns = [
    path("", views.index, name="index"),
    path("add_new", views.add_new, name="add_new"),
    path("password/<int:id>", views.get_password, name="password"),
    path("login/<int:id>", views.login_content, name="login_content"),
    path("delete/<int:id>", views.delete, name="delete"),
    path("new_folder", views.new_folder, name="new_folder"),
    path("edit_folder/<int:id>", views.edit_folder, name="edit_folder"),
    path('generate_password/<int:size>', views.generate_password, name="generator"),

]

Keymdall/theme/templates/theme/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>keymdall -{% block title %}{% endblock title %}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% tailwind_css %}
    <script src="{%static 'vault/script.js'%}"></script>
    <script src="{%static 'dashboard/dashboard-script.js'%}"></script>
    <script src="{%static 'theme/script.js'%}"></script>
</head>

<body class=" bg-gray-50 font-sans flex flex-col
overflow-x-hidden w-screen h-fit sm:h-screen">


    <nav class="flex w-screen h-14 items-center justify-around
    bg-teal-600 dark:bg-neutral-800 dark:text-white
     px-2 sm:px-4 py-2
    w-min-screen
    ">
        <div class="flex w-3/12">
                <img src="{%static 'icons/icon_big.png' %}" class="mr-3 h-14" alt="Logo" />
                <h2 class=" text-xl md:text-3xl font-bold flex items-center"><a href="{%url 'vault:index'%}">Key-mdall</a></h2>
        </div>
        <ul class="flex  w-5/12 justify-end items-center">
            {% if user.is_authenticated %}
            <li class="mx-2 font-bold hover:underline hover:text-white"><a
                    href="{%url 'dashboard:dashboard'%}">{{request.user | capfirst}}</a></li>
            <li class="mx-2 hover:underline hover:text-white"><a href="{%url 'dashboard:logout'%}">Logout</a></li>
            {%else%}
            <li class="mx-2"><a href="{%url 'dashboard:login'%}">Login</a></li>
            {%endif%}
            <li id="darkmode_toggle" class="md:absolute right-5 top-1.5 text-yellow-200
            bg-gray-800 dark:bg-teal-600
            border-0 rounded-lg p-2 px-3
            ">
            <svg id="moon" xmlns="http://www.w3.org/2000/svg" fill="yellow" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M21.752 15.002A9.718 9.718 0 0118 15.75c-5.385 0-9.75-4.365-9.75-9.75 0-1.33.266-2.597.748-3.752A9.753 9.753 0 003 11.25C3 16.635 7.365 21 12.75 21a9.753 9.753 0 009.002-5.998z" />
              </svg>
              <svg id="sun" xmlns="http://www.w3.org/2000/svg" fill="yellow" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 hidden">
                <path stroke-linecap="round" stroke-linejoin="round" d="M12 3v2.25m6.364.386l-1.591 1.591M21 12h-2.25m-.386 6.364l-1.591-1.591M12 18.75V21m-4.773-4.227l-1.591 1.591M5.25 12H3m4.227-4.773L5.636 5.636M15.75 12a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0z" />
              </svg>

              </li>
        </ul>
    </nav>


    <!-- ------- -->
    <!--box containing messages handled via Js absolute position top right Z-index above all-->
    <!-- django messages also trigger the Js custom function  -->
    <div id="message-box" class="absolute grid right-1 w-56 md:gap-2 mt-16 z-30
    font-semibold text-lg ">

        {% if messages %}
        {% for message in messages %}
        <script>
            flash_message("{{message}}", "{{message.tags}}");
        </script>
        {%endfor%}
        {%endif%}
    </div>

    <!-- ------- -->

    <div id="bg" class="bg-tile dark:bg-darktile h-full flex flex-col justify-between">

        <div class=" mt-8 mb-1 flex md:flex-row flex-col  items-center md:items-start
    md:max-h-full w-screen ">

            {% block body %}

            {% endblock body %}
        </div>
    </div>


    {% include "theme/footer.html" %}

    <!-- problem in tailwind, needs initialization of some colors to work by template inhertance btn-{folder.color} -->
    <div class="hidden">
        <button class="btn btn-teal"></button>
        <button class="btn btn-green"></button>
        <button class="btn btn-emerald"></button>
        <button class="btn btn-blue"></button>
        <button class="btn btn-cyan"></button>
        <button class="btn btn-red"></button>
        <button class="btn btn-orange"></button>
        <button class="btn btn-violet"></button>
        <button class="btn btn-pink"></button>
        <button class="btn btn-yellow"></button>
        <div class="bg-red-500"></div>
        <div class="green-popup"></div>
        <div class="red-popup"></div>
        <div class="bg-blue-600"></div>
    </div>
     <!-- color accent initialization because this tailwind version has issues with displaying from template inherited values login.folderColor -->
     <div class="hidden">
        <div class="bg-teal-600 dark:bg-teal-400"></div>
        <div class="bg-green-600 dark:bg-green-400"></div>
        <div class="bg-emerald-600 dark:bg-emerald-400"></div>
        <div class="bg-blue-600 dark:bg-blue-400"></div>
        <div class="bg-cyan-600 dark:bg-cyan-400"></div>
        <div class="bg-red-600 dark:bg-red-400"></div>
        <div class="bg-orange-600 dark:bg-orange-400"></div>
        <div class="bg-violet-600 dark:bg-violet-400"></div>
        <div class="bg-pink-600 dark:bg-pink-400"></div>
        <div class="bg-yellow-600 dark:bg-yellow-400"></div>
     </div>

</body>

</html>

Keymdall/theme/templates/theme/footer.html
{% load static %}


<footer class="z-10 p-4 bg-teal-500 sm:p-6 dark:bg-stone-800 w-full ">

    <div class="md:flex justify-between">
        <div class="flex mb-6 md:mb-0 ">
            <a href="https://cs50.harvard.edu/web/2020/projects/final/capstone/" class="flex items-center ">
                <img src="{%static 'icons/icon_big.png' %}" class="mr-3 h-14" alt="Logo" />
                <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Key-mdall</span>
            </a>
        </div>
        <div class="grid grid-cols-2 gap-8 sm:gap-6 sm:grid-cols-3">
            <div>
                <h2 class="mb-6 text-sm font-semibold text-gray-900 uppercase dark:text-white">Resources</h2>
                <ul class="text-gray-600 dark:text-gray-400">
                    <li class="mb-4">
                        <a href="https://icon-icons.com/" class="hover:underline">Icon-icons</a>
                    </li>
                    <li class="mb-4">
                        <a href="https://heroicons.com/" class="hover:underline">Hero icons</a>
                    </li>
                    <li>
                        <a href="https://randomuser.me/" class="hover:underline">RandomUser.me</a>
                    </li>
                </ul>
            </div>
            <div>
                <h2 class="mb-6 text-sm font-semibold text-gray-900 uppercase dark:text-white">Follow me</h2>
                <ul class="text-gray-600 dark:text-gray-400">
                    <li class="mb-4">
                        <a href="https://github.com/themesberg/dluca22" class="hover:underline ">Github</a>
                    </li>
                    <li>
                        <a href="https://twitter.com/LiukDee" class="hover:underline">Twitter</a>
                    </li>
                </ul>
            </div>
            <div>
                <h2 class="mb-6 text-sm font-semibold text-gray-900 uppercase dark:text-white">Legal</h2>
                <ul class="text-gray-600 dark:text-gray-400">
                    <li class="mb-4 opacity-30">
                        <a href="#" class="hover:underline">Privacy Policy</a>
                    </li>
                    <li>
                        <a href="https://cs50.harvard.edu/web/2020/projects/final/capstone/" class="hover:underline">Terms &amp; Conditions</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

</footer>