Keymdall/keymdall/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("vault.urls", namespace='vault')),
    path('dashboard/', include("dashboard.urls", namespace='dashboard')),

    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
]

Keymdall/vault/urls.py
from django.urls import path
from . import views

app_name = 'vault'

urlpatterns = [
    path("", views.index, name="index"),
    path("add_new", views.add_new, name="add_new"),
    path("password/<int:id>", views.get_password, name="password"),
    path("login/<int:id>", views.login_content, name="login_content"),
    path("delete/<int:id>", views.delete, name="delete"),
    path("new_folder", views.new_folder, name="new_folder"),
    path("edit_folder/<int:id>", views.edit_folder, name="edit_folder"),
    path('generate_password/<int:size>', views.generate_password, name="generator"),

]

Keymdall/vault/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import MaxValueValidator

from dashboard.models import User
from .encrypt_util import encrypt, decrypt




class Login(models.Model):
    """ Login model only required field is title, field encryption is managed in backend"""
    id = models.BigAutoField(primary_key=True)
    title = models.CharField(max_length=80)
    username = models.CharField(max_length=80, null=True, blank=True)
    password = models.CharField(max_length=80, null=True, blank=True)
    note = models.TextField(max_length=500, null=True, blank=True)
    folder = models.ForeignKey("Folder", on_delete=models.SET_NULL, null=True, blank=True, related_name="folder")
    protected = models.BooleanField(default=False)
    favorite = models.BooleanField(default=False)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=False, related_name="entries")
    uri = models.CharField(max_length=100, null=True, blank=True)


    def __str__(self):
        return self.title

    @property
    def passw_history(self):
        return History.objects.filter(login=self)

    @property
    def folderColor(self):
        return self.folder.color

    @property
    def noPassword(self):
        if decrypt(self.password) == "":
            return True
        else:
            return False


class History(models.Model):
    """ Stores former Login password fields when updated by user """
    id = models.BigAutoField(primary_key=True)
    old_passw = models.CharField(max_length=80)
    login = models.ForeignKey(Login, on_delete=models.CASCADE, related_name="previous_password")


    def __str__(self):
        return self.old_passw

# fixed set of colors accents for Folders
COLOR_CHOICES = (
    ('teal','TEAL'),
    ('green','GREEN'),
    ('emerald','EMERALD'),
    ('blue', 'BLUE'),
    ('cyan', 'CYAN'),
    ('red','RED'),
    ('orange','ORANGE'),
    ('violet','VIOLET'),
    ('pink','PINK'),
    ('yellow','YELLOW'),
)

class Folder(models.Model):
    """ Folder to organize Logins/Items, default color is cyan, user has 10 color choices"""
    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=32, blank=False, null=False)
    color = models.CharField(max_length=8,choices=COLOR_CHOICES, default='cyan')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=False, related_name="folders")

    def __str__(self):
        return self.name

Keymdall/vault/forms.py
from .models import Login , Folder
from django.forms import ModelForm, Textarea, PasswordInput, Select , TextInput
from .encrypt_util import encrypt, decrypt

class LoginForm(ModelForm):

    class Meta:
        model= Login
        fields = ('title', 'username', 'password', 'note', 'folder', 'protected', 'favorite', 'uri',)
        widgets = {
            'title': TextInput(attrs={"class":" "}),
            'username': TextInput(attrs={"class":" "}),
            'password': PasswordInput(render_value=True, attrs={"class":" border-2"}),
            'note': Textarea(attrs={'rows':6, 'placeholder':"Add notes here...", 'class':' border-2 '}),
            'uri': TextInput(attrs={'placeholder': "url...", "class":" border-2 "}),
            'folder': Select(attrs={"class":" border-2 "})
        }

    # initialize Form model, pass argument (user=request.user)
    # from kwargs get 'user', in 'folder' field returns queryset of choices limited by folders owned by current user
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        # LATER control this next line (cos'è?)
        super(LoginForm, self).__init__(*args,**kwargs)
        # ?? not set to None
        self.fields['folder'].initial = 'None'
        self.fields['folder'].queryset = Folder.objects.filter(owner=user)



class FolderForm(ModelForm):
    class Meta:
        model = Folder
        fields = ('name', 'color',)
        widgets = {
            'name': TextInput(attrs={'placeholder':"Folder Name...", 'class':' border-2 border-violet-500'}),
            'color': Select(attrs={'class':'flex rounded-xl mx-2 p-1 text-black'})
        }
        labels = {
            'color': "Folder color: "
        }

Keymdall/vault/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import requires_csrf_token
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect, JsonResponse
from django.db.models.functions import Lower

from django.contrib import messages
import json

from .models import Login, History ,Folder
from dashboard.models import User
from .forms import LoginForm, FolderForm

from .utils import password_generator, format_uri
from .encrypt_util import encrypt, decrypt


# ===================================================

@login_required(login_url=reverse_lazy('dashboard:login'), redirect_field_name=None)
def index(request):

    # if there is a query for each of these fields
    folder_query = request.GET.get('folder')
    filter = request.GET.get('filter')
    search = request.GET.get('q')

    if folder_query:
        # if query is from btn "none" category, selects only items not in folder
        if folder_query == "none":
            logins = Login.objects.filter(folder__isnull=True, owner=request.user)
        # else, filter where folder name is the one in the query
        else:
            logins = Login.objects.filter(folder__name=folder_query, owner=request.user)
    # if query is for fav items, selects only those
    elif filter == "fav":
        logins = Login.objects.filter(owner=request.user, favorite=True)
    elif filter == "logins":
        logins = Login.objects.filter(favorite=True, owner=request.user)
    # elif filter == "notes":
    #     logins = Note.objects.filter(owner=request.user).order_by('title')
    # if the query is a ?q search request, selects ones where the title contains the word in search (insensitive contains)
    elif search:
        logins = Login.objects.filter(title__icontains=search, owner=request.user)
    # else selects all logins
    else:
        logins = Login.objects.filter(owner=request.user).order_by('title')


    # builds forms and folder qset and adds to the context
    login_form = LoginForm(user=request.user)
    folder_form = FolderForm()
    folders = (request.user).folders.all().order_by(Lower('name'))
    context = {  'logins':logins,
                 'form':login_form,
                 'folder_form': folder_form,
                 'folders': folders}
                #  return index page with context
    return render(request, 'vault/index.html', context=context)


# ===================================================


def add_new(request):
    """add <str:type> per aggiungere sia login che note"""
    if request.method == "POST":

        login_form = LoginForm(request.POST, user=request.user)

        if login_form.is_valid():
            # get uri field from form
            uri = format_uri(login_form.instance.uri)
            login_form.instance.uri = encrypt(uri)


            # encrypt also password and note then save
            # if field is "None", encrypt empty space ""
            passw = login_form.instance.password
            note = login_form.instance.note
            login_form.instance.password = encrypt(login_form.instance.password)
            login_form.instance.note = encrypt(login_form.instance.note)

            login_form.instance.owner = request.user
            login_form.save()
            # send message then redirect to index
            messages.success(request, "New element created!")
        return HttpResponseRedirect(reverse('vault:index'))

    else:
        return HttpResponseRedirect(reverse('vault:index'))

# ===================================================

# or @csrf_protect (cambia behavior on rejection)
@requires_csrf_token
def get_password(request, id):
    """ fare controllo se il login è protected presentare richiesta pin"""
    #LATER  id = int(id, 16)
    # gets the pin from request, if it is not protected, pin is set to false by client.js
    pin = json.loads(request.body)
    # TODO convert to @property so that it can be decrypted from models.py
    user_pin = decrypt(request.user.pin)
    # try if login is existing
    try:
        login = Login.objects.get(id=id)
    except:
        return JsonResponse({"denied":"Failed request", "message":"This item does not exist!"})

    if request.user != login.owner:
        return JsonResponse({"denied":"unauthorized", "message":"You are not the owner"})



    # if login is protected and pin wasn't provided (may change and just compare if pin is equal to User.pin)
    if login.protected and not pin:
        return JsonResponse({"denied":"unauthorized", "message":"Item locked! PIN is required"})

    elif login.protected and pin != user_pin:
        return JsonResponse({"denied":"unauthorized", "message":"Incorrect PIN"})
    else:

        password = decrypt(login.password)
        return JsonResponse({"success": "successful request", "content": password})

# ===================================================

@requires_csrf_token
def login_content(request, id):
    """GET request shows the Item content in a form, POST request edits the element
    both check wether the Item exists and the user is the owner
    """
    # TODO change id to hex

    try:
        login = Login.objects.get(id=id, owner=request.user)
    except:
        messages.error(request, "Unauthorized: You are not the owner", fail_silently=True)
        return HttpResponseRedirect(reverse('vault:index'))

    if request.method == "GET":
        # decrypt the fields before running instances of login (uses _meta attribute to compile form)
        # login = login.decrypted (this property does not work, does not return a model instance but a dictionary)
        login.password = decrypt(login.password)
        login.uri = decrypt(login.uri)
        login.note = decrypt(login.note)

        # 'user' **kwargs is used to return the folder instance beloging to the user
        edit_form = LoginForm(instance=login, user=request.user)

        context = {
            'title': login.title,
            'item_id': id,
            'form':edit_form,
            'history': [decrypt(str(old_pw)) for old_pw in login.passw_history]

        }
        return render(request, 'vault/login_content.html', context=context)

    # decrypt old password to compare for changes

    elif request.method == "POST":
        """ edit request, if password changed, stores the old password in History table """
        old_password = login.password
        old_password_clear = decrypt(old_password)
        edit_form = LoginForm(request.POST, instance=login, user=request.user)

        if edit_form.is_valid():

            # Check if new password is different from old password, and is NOT null, then stores old_passw in History table

            new_pw = edit_form.instance.password
            #
            if old_password_clear != new_pw and old_password_clear != "" :
                # if cleartext old password is not equal to the new password, store login.password(not decrypted) in the history model
                History.objects.create(old_passw=old_password, login=login)

            edit_form.instance.password = encrypt(edit_form.instance.password)
            uri = format_uri(edit_form.instance.uri)
            edit_form.instance.uri = encrypt(uri)
            edit_form.instance.note = encrypt(edit_form.instance.note)
            edit_form.save()

            messages.success(request, 'Successful edit', fail_silently=True)
            return HttpResponseRedirect(reverse('vault:login_content', args=[id]))
        # if messages not valid
        else:
            messages.error(request, 'Invalid form', fail_silently=True)
            return HttpResponseRedirect(reverse('vault:login_content', args=[id]))


# ===================================================


def generate_password(request, size):
    try:
        passw = password_generator(size)
        return JsonResponse({"success":"successful request", "message":'Password generated!', 'password': passw})
    except:
        return JsonResponse({"denied": "error", "message": 'An unexpected error occurred'})

# ===================================================

@requires_csrf_token
def delete(request,id):
    """cancella l'elemento """
    if request.method == "DELETE":
        try:
            login = Login.objects.get(id=id)
        except:
            return JsonResponse({"denied":'Failed request', "message":"This item does not exist!"})


        if login.owner == request.user:
            login.delete()
            return JsonResponse({"success":"Successful requesta", "message" : 'deleted successfully'})
        else:
            return JsonResponse({"denied":'Failed request', "message" : 'You are not authorized!'})


# ===================================================


def new_folder(request):
    if request.method == "POST":
        form = FolderForm(request.POST)

        if form.is_valid():
            form.instance.owner = request.user
            form.save()
        messages.success(request, "Folder created", fail_silently=True)
        return HttpResponseRedirect(reverse('vault:index'))

# ===================================================


def edit_folder(request, id):
    """from async request GET method returns name of folder if present
        PUT request, gets body content of input field and assigns to the model
        DELETE request deletes the db entry"""

    # on fetch get request to get the pre filled field checks if folder exists and if request.user is owner
    # protection for html hacking
    try:
        folder = Folder.objects.get(id=id)
    except:
        return JsonResponse({"denied": "request denied", "message":"Folder does not exist"})

    if folder.owner != request.user:
        return JsonResponse({"denied":"request denied", "message":"You are not the owner!"})

    if request.method == "PUT":
        new_name = json.loads(request.body)
        folder.name = new_name
        folder.save()

Keymdall/vault/templates/vault/custom_form.html
{% load static %}


            <span class="flex justify-end gap-4 items-center">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2"
                    stroke="currentColor" class="w-8 h-8 text-red-300">
                    <path stroke-linecap="round" stroke-linejoin="round"
                        d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z" />
                </svg> {{form.favorite}}

                {%if user.pin%}
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                    stroke="currentColor" class="w-6 h-6">
                    <path stroke-linecap="round" stroke-linejoin="round"
                        d="M16.5 10.5V6.75a4.5 4.5 0 10-9 0v3.75m-.75 11.25h10.5a2.25 2.25 0 002.25-2.25v-6.75a2.25 2.25 0 00-2.25-2.25H6.75a2.25 2.25 0 00-2.25 2.25v6.75a2.25 2.25 0 002.25 2.25z" />
                </svg>
                {{form.protected}}

                {%else%}
                <div class="absolute mr-52">

                    <p class="text-sm text-red-700">PIN not set You can't protect the item</p>
                </div>

                {%endif%}
            </span>

            <div class="flex gap-4 ">
                <div class="">
                    <p class="italic dark:text-white ml-2 font-bold">Title:</p>
                    {{form.title}}
                </div>

            </div>
            <div class="flex items-end gap-4 ">

                <div>
                    <p class="italic dark:text-white ml-2 font-bold">Username:</p>
                    <div class="flex items-center">
                        {{form.username}}
                        <img id="generate_username" src="{% static 'icons/random.svg' %}" alt="randomize"
                            class=" w-8 h-8 bg-yellow-500 rounded-full m-1">
                    </div>
                </div>

            </div>
            <div class="flex content-evenly gap-4 ">

                <div>
                    <p class="italic dark:text-white ml-2 font-bold">Password:</p>
                    <div class="flex items-center gap-2">
                        {{form.password}}


                        <div class="bg-green-200 bg-opacity-50 flex p-2 border border-green-600 rounded-lg">
                            <img id="generate_password" src="{% static 'icons/random.svg' %}" alt="randomize"
                                class=" w-8 h-8 bg-green-500 rounded-full m-1">
                            <input class="rounded-lg text-center border-green-600 p-0 w-12" type="number"
                                placeholder="size" step="1" min="3" max="24" id="size" />
                        </div>

                    </div>
                </div>

            </div>
            <div class="flex items-end gap-4 ">

                <div>
                    <p class="italic dark:text-white ml-2 font-bold">Url:</p>
                    <div class="flex items-end gap-2">
                        {{form.uri}}
                    </div>
                </div>

            </div>
            <div class="flex items-center justify-end gap-2">
                <p class="italic dark:text-white ml-2 font-bold">Folder: </p>
                {{form.folder}}


            </div>
            <div class="flex items gap-4 ">

                <div class="flex flex-col mb-1">
                    <p class="italic dark:text-white ml-2 font-bold">Notes:</p>
                    {{form.note}}
                </div>

            </div>

Keymdall/vault/templates/vault/index.html
{% extends "theme/base.html" %}

{% block title %} vault {% endblock title %}

{% block body %}

<sidebar class=" flex flex-col w-10/12 md:w-64 h-max-screen md:flex-shrink-0 md:m-9
justify-around
" aria-label="Sidebar">

    {% include "vault/sidebar.html" %}
</sidebar>

<!-- main col in index with +items btn and the content boxes -->
<div id="main" class="flex flex-col w-8/12 flex-shrink-0 md:max-h-screen
flex-grow-1 items-center">

    <button id="show_login_form" class="btn btn-green mb-3">New Login</button>

    <!-- div for the col containing the item boxes -->
    <div class="scrollable vault-content

    overflow-y-auto h-4/5 overflow-x-hidden
    flex flex-col items-center md:w-8/12">
        {% for login in logins %}
        {% include "vault/login_box.html" %}
        {%empty%}
        <div class="flex justify-center items-center h-48">
            <p class="text-2xl dark:text-white">There are no logins here</p>

        </div>
        {%endfor%}

    </div>
</div>



<div id="modals" class="z-10">
    {% include "vault/vault_modals.html" %}
</div>

{% endblock body %}

Keymdall/vault/templates/vault/login_box.html
{%load static%}


<div id="{{login.id}}" class="login_box bg-white" data-type="login"
    data-protection="{% if login.protected == True %}locked{%else%}unlocked{%endif%}">

    <!-- sometimes doesn't get initialized by tailwind until hardcoding the color first, maybe check later for css building -->
    <!-- color accent on left side of box for folder color -->
    {% if login.folder %}
    <div class="w-2 h-full rounded-xl overflow-hidden absolute p-0 -m-3
         bg-{{login.folderColor}}-600 dark:bg-{{login.folderColor}}-400 opacity-70">


    </div>

    {%endif%}

    <!-- if login favorite, yellow start on top-right of box -->
    {% if login.favorite %}

    <div class="absolute right-1 top-0 text-4xl text-yellow-400">&#9733;</div>
{%endif%}

    <div class="mx-auto">
        <!-- flex div for title and title label -->
        <div class="flex flex-col items-center">
            <p class="border-b-2 border-teal-500 font-semibold text-gray-700  dark:text-blue-300 ">
                {{login.title | capfirst}}
            </p>
            <p class="text-xs text-teal-800opacity-80 ">Title</p>


        </div>
    </div>
    <div>

        <!-- container for username and password -->
        <div class="flex justify-around flex-wrap overflow-hidden ">

            <!-- username container flex-col for username and username label -->
            <div
                class="username-copy flex flex-col items-center m-3
                 border-b-2 border-transparent
                 hover:opacity-80 hover:border-teal-500">
                <p class="italic leading-3 text-green-600 ">
                    {% if not login.username %}
                    " "
                    {%else%}
                    {{login.username}}
                    {%endif%}
                </p>
                <p class="text-xs text-teal-800 dark:text-teal-400 opacity-80 ">User</p>

            </div>
            {% if not login.noPassword %}
            <img class="copy-passw
                {% if login.protected == True %} border-2 border-red-500 -pb-2 p-2 rounded-lg {%endif%}
                " src="{%static 'icons/key.svg'%}" alt="password">

            {%else%}
            <img class="opacity-5" src="{%static 'icons/key.svg'%}" alt="unset">
            {%endif%}

            <!-- TODO don't include value of password, listen for click and send request to backend and add to clipboard -->
        </div>
    </div>
</div>

Keymdall/vault/templates/vault/login_content.html
{% extends "theme/base.html" %}
{% block title %} {{title}}{% endblock title %}
{% load static %}


{% block body %}

<div class="flex flex-col md:flex-row items-center md:items-start md:justify-around
 bg-white dark:bg-neutral-800 bg-opacity-90 w-full mx-5 rounded-lg">
    <div id="item_content" class="w-6/12 flex justify-center">

        <form id="login_form" action="{%url 'vault:login_content' item_id%}" method="post"
            class="p-2 md:p-6 flex flex-col ">
            {%csrf_token%}

            <div class=" scale-75 md:transform-none">{% include "vault/custom_form.html" %}</div>
            <input type="submit" name="add_login" value="Edit login" class="btn btn-teal mx-auto ">

        </form>

    </div>


    <!-- side bar -->

    <div id="settings" class="w-72">
        <h3 class="text-lg font-bold bg-teal-600 bg-opacity-30 border border-teal-600 rounded-t-lg flex justify-center dark:text-white">Settings:</h3>

        <button id="delete_item" value="{{item_id}}" class="flex mt-3 mx-auto btn btn-red">Delete Item</button>

        {% if history %}
        <div id="password_history" class="my-2 flex flex-col mx-auto justify-center rounded-lg ">

            <div class="text-lg font-bold bg-teal-600 bg-opacity-30 border border-teal-600 rounded-lg flex justify-center dark:text-white
                    ">Previous passwords:
                    <span id="dropdown" class="mx-2 ">&#9662;</span>
                </div>


                <ul id='history_list' class="hidden list-disc list-inside p-1
                rounded-b-lg dark:bg-neutral-600">
                    {% for old_pw in history %}
                    <li class="italic text-blue-800 dark:text-cyan-400
                    hover:bg-teal-100 hover:dark:bg-opacity-10  hover:cursor-pointer
                    my-2">{{old_pw}}</li>
                    {%endfor%}
                </ul>

            {%else%}

            <p class="text-gray-400 my-2 italic">No previous passwords: </p>
        </div>
        {%endif%}
    </div>

    <!-- login content modal -->

    <div id="delete_item_confirm" class="fixed hidden inset-0 bg-gray-600 bg-opacity-50 ">
        <div class="relative my-auto mx-auto
        text-center
        p-5 border-2 border-red-500 shadow-lg rounded-md bg-red-100 ">
                <h2 class="text-lg font-bold text-red-500">&#9888 DELETE ITEM &#9888<h2>
                <p class="my-2 text-red-700">Are you sure?</p>

            <button value="confirm" class="btn btn-green">Confirm</button>
            <button value="dismiss" class="btn btn-red">Dismiss</button>

        </div>
    </div>

</div>


<script>
if(document.querySelector('#dropdown')){
    const dropdown = document.querySelector('#dropdown')
    dropdown.parentNode.addEventListener('click', () =>{
        const list = document.querySelector('#history_list')
        if(list.classList.contains('hidden')){
            list.classList.remove('hidden');
            dropdown.innerHTML = "&#9652;";
        }
        else{
            list.classList.add('hidden')
            dropdown.innerHTML = "&#9662;";
            }

    })

}
</script>

{% endblock body %}

Keymdall/vault/templates/vault/vault_modals.html
{% load static %}

<!-- TODO fix input color in darkmode -->

<!-- pin form modal -->
<div id="pin_modal" class="fixed hidden inset-0 bg-gray-600 bg-opacity-50">
    <div class="relative my-auto mx-auto p-5 border-2 border-green-500 shadow-lg rounded-md bg-green-50">
        <header class="flex relative -top-5 justify-center
         bg-green-200  border-2 border-t-0 rounded-b-lg border-green-500
         text-green-900 font-bold "> Submit PIN</header>
        <form>
            <input autofocus id="pin_input" type="text" placeholder="PIN" maxlength="4"
                class="rounded-lg border-green-500 w-32">
            <input type="submit" value="OK" class="btn btn-green">
        </form>
    </div>
</div>


<!-- new login modal -->
<div id="new_login_modal" class="absolute hidden inset-0 bg-gray-600 bg-opacity-50 flex flex-col items-center justify-center ">

    <div class=" relative p-2 md:p-5
    scale-75 md:transform-none
    shadow-lg rounded-2xl border-2 border-blue-500 bg-blue-50
    dark:bg-neutral-800 ">

        <header class="flex relative -top-2 md:-top-5 justify-center
         bg-blue-200  border-2 border-t-0 rounded-b-lg border-blue-500
         text-blue-900 font-bold ">
            New Login
        </header>

        <form id="login_form" action="{%url 'vault:add_new'%}" method="post" class="p-6 flex flex-col">
            {%csrf_token%}
            {% include "vault/custom_form.html" %}


            <input type="submit" name="add_login" class="btn btn-teal ">
        </form>

    </div>

</div>
<!-- new folder modal -->

<div id="new_folder_modal" class="fixed hidden inset-0 bg-gray-600 bg-opacity-50 ">
    <div class="relative my-auto mx-auto p-5 border-2 border-violet-500 shadow-lg rounded-md bg-gray-200 ">
        <header class="flex relative -top-5 justify-center
         bg-violet-200  border-2 border-t-0 rounded-b-lg border-violet-500
         text-violet-900 font-bold "> New Folder</header>
        </header>
        <form action="new_folder" method="post" class="flex flex-col">
            {%csrf_token%}


            {{folder_form.name}}
            <div class="text-violet-700 text-lg flex items-center my-1">
                {{folder_form.color.label}}{{folder_form.color}}
            </div>
            <div class="flex justify-end">
                <input type="submit" class="btn btn-violet p-1 my-1 ">
            </div>
        </form>

    </div>
</div>

<!-- edit folder modal -->

<div id="edit_folder_modal" class="fixed hidden inset-0 bg-gray-600 bg-opacity-50 ">
    <div class="relative my-auto mx-auto p-5 border-2 border-yellow-500 shadow-lg rounded-md bg-yellow-100 ">
        <header class="flex relative -top-5 justify-center
         bg-yellow-200  border-2 border-t-0 rounded-b-lg border-yellow-500
         text-yellow-900 font-bold "> Edit Folder</header>
         <form value="">

                <input type="text" name="name" placeholder="Edit Name..." class="rounded-lg border-2 border-yellow-500 " maxlength="32" required id="current_folder_name">

                <div class="flex justify-around">

                    <input type="submit" class="btn btn-red p-1 my-1" value="Delete">
                    <input type="submit" class="btn btn-yellow p-1 my-1" value="Edit">
                </div>
        </form>


    </div>
</div>