Keymdall/dashboard/urls.py
from django.urls import path, include
from . import views

app_name = 'dashboard'

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("login", views.login_form, name="login"),
    path("register", views.register_form, name="register"),
    path("logout", views.logout_user, name="logout"),
    path("edit_pin", views.edit_pin, name="edit_pin"),
    path("set_pin", views.set_pin, name="set_pin"),
    path("change_masterpassword", views.change_masterpassword, name="change_masterpassword"),
    path("change_email", views.change_email, name="change_email"),
    path("delete_account", views.delete_account, name="delete_account"),


]

Keymdall/keymdall/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("vault.urls", namespace='vault')),
    path('dashboard/', include("dashboard.urls", namespace='dashboard')),

    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
]

Keymdall/vault/urls.py
from django.urls import path
from . import views

app_name = 'vault'

urlpatterns = [
    path("", views.index, name="index"),
    path("add_new", views.add_new, name="add_new"),
    path("password/<int:id>", views.get_password, name="password"),
    path("login/<int:id>", views.login_content, name="login_content"),
    path("delete/<int:id>", views.delete, name="delete"),
    path("new_folder", views.new_folder, name="new_folder"),
    path("edit_folder/<int:id>", views.edit_folder, name="edit_folder"),
    path('generate_password/<int:size>', views.generate_password, name="generator"),

]

Keymdall/dashboard/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinLengthValidator

from vault.encrypt_util import decrypt



class User(AbstractUser):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=80, null=False, blank=False, unique=True)
    pin = models.CharField(max_length=6, validators=[MinLengthValidator(4)], null=True, blank=True)
    # TODO IMPORTANT change to CharFiled to enable hashing and add validators in the input field

    USERNAME_FIELD: 'username'

    def __str__(self):
        return self.username

    @property
    def num_logins(self):
        return self.entries.all().count()

    @property
    def num_folders(self):
        return self.folders.all().count()

    @property
    def get_pin(self):
        return decrypt(self.pin)

Keymdall/dashboard/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib import messages

from django.db.utils import IntegrityError

from vault.encrypt_util import encrypt, decrypt

from .models import User
# from .forms import User

@login_required(login_url=reverse_lazy('dashboard:login'), redirect_field_name=None)
def dashboard(request):
    """index file for the dashboard, display all user's stats and user settings like pin, email change, password change"""

    folders = request.user.folders.all()
    context = {'folders': folders}
    return render(request, 'dashboard/userpage.html', context=context)

    pass

# ===================================================

def login_form(request):
    """ logs in a user if correct + message , else sends message in the same form"""
    if request.method == "GET":
        return render(request, 'dashboard/login.html')

    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        if not username or not password :
            messages.error(request, f"All fields must be provided", fail_silently=True )
            return render(request, 'dashboard/login.html')


        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            messages.success(request, f"Logged-in", fail_silently=True )
            return HttpResponseRedirect(reverse('vault:index'))
        else:
            messages.error(request, f"Invalid username and/or password", fail_silently=True )
            return render(request, 'dashboard/login.html')


# ===================================================

def logout_user(request):
    logout(request)
    """ logs out current user and redirects to login page"""
    return HttpResponseRedirect(reverse('dashboard:login'))


# ===================================================

def register_form(request):
    """ register a new user"""
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # can't be empty field
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]

        # not accepting empty fields
        if not username or not email or not password or not confirmation:
            messages.error(request, "ALL fields must be submitteed", fail_silently=True )

            return render(request, 'dashboard/login.html')
        if password != confirmation:
            messages.error(request, "Passwords MUST match", fail_silently=True )

            return render(request, 'dashboard/login.html')

        try:
            user= User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            messages.error(request, f"{username} is already taken", fail_silently=True )
            return render(request, 'dashboard/login.html')

        login(request, user)
        messages.success(request, f"Succesful registration. Welcome {username}", fail_silently=True )

        return HttpResponseRedirect(reverse('vault:index'))


# ===================================================

def edit_pin(request):
    if request.method == "POST":

        user = request.user
        # pw, old pin, new pin and confirmation derived from the form
        master_password = request.POST['master_password']
        old_pin = request.POST['old_pin']
        new_pin = request.POST['new_pin']
        confirmation = request.POST['confirm_pin']


        # if check password failed (using hashed check comparison)
        if not user.check_password(master_password):
            messages.error(request, 'Master Password was incorrect',fail_silently=True)
            return HttpResponseRedirect(reverse('dashboard:dashboard'))

        # if form old_pin as cleartext IS NOT decrypted(user.pin)
        elif old_pin != decrypt(user.pin):
            messages.error(request, 'Current PIN was incorrect',fail_silently=True)
            return HttpResponseRedirect(reverse('dashboard:dashboard'))

        # if pin and confirmation don't match, or pin is not 4 digits
        elif new_pin != confirmation or len(new_pin) != 4:
            messages.error(request, 'New PIN check failed',fail_silently=True)
            return HttpResponseRedirect(reverse('dashboard:dashboard'))
        # if new PIN is the same as old PIN
        elif new_pin == old_pin:
            messages.warning(request, 'PIN not updated: it was the same as the current one',fail_silently=True)
            return HttpResponseRedirect(reverse('dashboard:dashboard'))

        # if clears all conditions, encrypt pin and save
        else:
            user.pin = encrypt(new_pin)
            user.save()
            messages.success(request, 'PIN updated',fail_silently=True)

            return HttpResponseRedirect(reverse('dashboard:dashboard'))


# ===================================================

def set_pin(request):
    if request.method == "POST":

        user = request.user
        new_pin = request.POST['new_pin']

        if len(new_pin) != 4:
            messages.error(request, 'PIN must be 4 digits',fail_silently=True)

            return HttpResponseRedirect(reverse('dashboard:dashboard'))

        user.pin = encrypt(new_pin)
        user.save()

        messages.success(request, 'PIN set',fail_silently=True)
        return HttpResponseRedirect(reverse('dashboard:dashboard'))


# ===================================================

def change_masterpassword(request):
    if request.method == "POST":
        user = request.user
        email = request.POST['email']
        current_password = request.POST['current_password']
        pin = request.POST['pin']

        new_password = request.POST['new_password']
        confirmation = request.POST['confirmation']

        if new_password != confirmation:
            messages.error(request, "Passwords do not match",fail_silently=True)
            return HttpResponseRedirect(reverse('dashboard:dashboard'))


        email_check = email == user.email
        pin_check = pin == user.get_pin
        pw_check = user.check_password(current_password)

        if email_check and pin_check and pw_check:
            user.set_password(new_password)
            user.save()

            messages.success(request, 'Password updated!',fail_silently=True)
            messages.success(request, 'Log back in',fail_silently=True)
            return HttpResponseRedirect(reverse('dashboard:login'))

        else:
            messages.error(request, 'Form check failed',fail_silently=True)
            messages.error(request, 'Password unchanged',fail_silently=True)

            return HttpResponseRedirect(reverse('dashboard:logout'))



# ===================================================

def change_email(request):
    if request.method == "POST":
        user = request.user
        new_email = request.POST['email']
        password = request.POST['password']


        if user.check_password(password) :
            user.email = new_email
            user.save()
            messages.success(request, 'Email updated',fail_silently=True)
            return HttpResponseRedirect(reverse('dashboard:dashboard'))
        else:
            messages.error(request, 'Failed check',fail_silently=True)
            messages.error(request, 'Email unchanged',fail_silently=True)
            return HttpResponseRedirect(reverse('dashboard:dashboard'))


# ===================================================


def delete_account(request):
    if request.method == "POST":
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']

        # matching fields to get bool values
        username_match = username == request.user.username
        email_match = email== request.user.email
        pw_match = request.user.check_password(password)

        # if all 3 bool values are true, process delete()
        if username_match and email_match and pw_match:
            request.user.delete()
            messages.success(request, "Account deleted.")
            return HttpResponseRedirect(reverse('dashboard:login'))

        messages.error(request, "Not deleted.")
        messages.error(request, "Form did not match.")
        return HttpResponseRedirect(reverse('dashboard:dashboard'))

Keymdall/dashboard/templates/dashboard/dashboard_modals.html
{% load static %}

<!-- LATER might add this forms ad ModelForms -->

<!-- change "hidden" to "grid" in modal wrapper to keep displaying it during UI editing/testing -->

<!-- template for the form to update PIN (linked to #update_pin button only showing if a PIN is already set) -->
<div id="pin_update_modal" class="fixed hidden z-20 inset-0 bg-gray-700 bg-opacity-50">

    <div id="pin_update_form" class="relative my-auto mx-auto p-8
     rounded-lg bg-yellow-100 bg-opacity-90 shadow-2xl
    text-yellow-800 font-bold">
        <form action="{%url 'dashboard:edit_pin'%}" method="post" class="flex flex-col items-center">
            {%csrf_token%}
            <p>== Enter your password and current PIN ==</p>
            <div id="password_check" class="flex">
                <input class="mb-1 rounded-lg" type="password" name="master_password"
                            placeholder="Your Master Password">
            </div>

            <div id="pin_check" class="flex">
                <input class="mb-1 rounded-lg" type="password" name="old_pin" maxlength="4" placeholder="Your current PIN">
            </div>

            <p>== Enter your new PIN ==</p>

            <div id="new_pin" class="flex">
                <input class="mb-1 rounded-lg" type="password" name="new_pin" maxlength="4"
                            placeholder="Insert 4 digits...">
            </div>
            <div id="pin_confirmation" class="flex">
                <input class="mb-1 rounded-lg" type="password" name="confirm_pin" maxlength="4" placeholder="Insert new PIN again..."></div>

            <input type="submit" value="Update PIN" class="btn btn-yellow mt-4 bg-yellow-600">
        </form>
    </div>
</div>


<!-- template for the form to SET PIN if user hasn't yet -->
<div id="pin_set_modal" class="fixed hidden z-20 inset-0 bg-gray-600 bg-opacity-50">

    <div id="pin_set_form" class="relative my-auto mx-auto p-8
    rounded-lg bg-yellow-200 bg-opacity-90 shadow-2xl
    text-yellow-800 font-bold">
        <form action="{%url 'dashboard:set_pin'%}" method="post" class="flex flex-col items-center">
            {%csrf_token%}
            <p>== Enter new PIN ==</p>

            <div class="flex"><input class="my-1 rounded-lg" type="password" name="new_pin" maxlength="4" placeholder="Insert 4 digits..."></div>
            <input type="submit" value="Set PIN" class="btn btn-blue">

        </form>
    </div>
</div>

<!-- template for the form to change password -->
<div id="change_masterPassword_modal" class="fixed hidden z-20 inset-0 bg-gray-600 bg-opacity-50">
    <div id="delete_form" class="relative my-auto mx-auto p-4
    rounded-lg bg-violet-200 bg-opacity-90 shadow-2xl
    text-violet-800 font-bold
    w-fit flex flex-col items-center gap-2">

        <p class="text-xl md:text-2xl">== Change Master Password ==</p>
        <p class="text-sm md:text-md">Insert Email, PIN and current password for confirmation</p>
        <form action="{% url 'dashboard:change_masterpassword' %}" method="post"
        class="flex flex-col gap-2">
            {%csrf_token%}
            <input type="email" name="email" placeholder="Email" class="rounded-lg">
            <div id="pin_check" class="flex">
                <input class="mb-1 rounded-lg" type="password" name="pin" maxlength="4" placeholder="PIN">
            </div>

            <div class="flex">
                <input type="password" name="current_password" placeholder="Current Password" class="rounded-lg">
            </div>

            <p>Submit your new password</p>
            <div class="flex">
                <input type="password" name="new_password" placeholder="New Password" class="rounded-lg">
            </div>
            <div class="flex">
                <input type="password" name="confirmation" placeholder="Confirm Password" class="rounded-lg">
            </div>
            <input type="submit" class="btn btn-violet flex mx-auto" value="Change Master Password">
        </form>

    </div>
</div>


<!-- template for the form to change email -->

<div id="change_email_modal" class="fixed hidden z-20 inset-0 bg-gray-600 bg-opacity-50">
    <div id="delete_form" class="relative my-auto mx-auto p-4
    rounded-lg bg-green-200 bg-opacity-90 shadow-2xl
    text-green-800 font-bold
    w-fit flex flex-col items-center gap-2 ">

        <p class="text-2xl">== Change user Email ==</p>
        <form action="{% url 'dashboard:change_email' %}" method="post"
        class="flex flex-col gap-2">
            {%csrf_token%}
            <input type="email" name="email" placeholder="New Email" class="rounded-lg">
            <p class="flex justify-centertext-sm mb-1">Confirm with password</p>
            <div class="flex">
                <input type="password" name="password" placeholder="Master Password" class="rounded-lg">
            </div>
            <input type="submit" class="btn btn-green flex mx-auto" value="Change Email">
        </form>

    </div>
</div>

<!-- template for the form to DELETE account -->
<div id="delete_account_modal" class="fixed hidden z-20 inset-0 bg-gray-600 bg-opacity-50">
    <div id="delete_form" class="relative my-auto md:mx-auto p-4
    rounded-lg bg-red-300 bg-opacity-90 shadow-2xl
    text-red-800 font-bold
     w-fit mx-1 flex flex-col items-center gap-2">

        <p class="text-2xl">== Are you sure? ==</p>
        <p class="flex flex-wrap w-2/3 text-sm ">This action is irreversible, please enter your username, email and password to confirm deletion</p>
        <form action="{% url 'dashboard:delete_account' %}" method="post"
        class="flex flex-col gap-2 ">
            {%csrf_token%}
            <div class="flex"><input type="text" name="username" placeholder="Username" class="rounded-lg"></div>
            <div class="flex"><input type="text" name="email" placeholder="Email" class="rounded-lg"></div>
            <div class="flex">
                <input type="password" name="password" placeholder="Master Password" class="rounded-lg">
            </div>
            <input type="submit" class="btn btn-red flex mx-auto" value="Delete Account">
        </form>

    </div>
</div>

Keymdall/dashboard/templates/dashboard/login.html
{% extends "theme/base.html" %}
{% load static %}



{% block title %}
Login
{% endblock title %}

{% block body %}

<div class="flex flex-col items-center w-full h-full m-32 ">
    <!-- login/register box -->
    <div class="flex flex-row justify-around gap-3">
        <button id="toggle_login" class="btn btn-green" rounded">Login</button>
        <button id="toggle_register" class="btn btn-yellow">Register</button>
    </div>
    <div id="login_form" class="flex flex-col items-center gap-2">
        <!-- login -->
        <p class="text-lg font-bold dark:text-cyan-300 mt-5">Log-in</p>
        <form action="{%url 'dashboard:login'%}" method="post" class=" flex flex-col gap-2">
            {%csrf_token%}
            <div>
                <input autofocus type="text" name="username" placeholder="Username" class="rounded-lg">
            </div>
            <div class="flex">
                <input type="password" name="password" placeholder="Password" class="rounded-lg">

            </div>
            <input type="submit" value="Login" class="btn btn-blue flex mx-auto">
            <!-- <div class="bg-blue-500">initialize</div> -->
        </form>


    </div>
    <div id="register_form" class=" hidden flex flex-col items-center gap-2">
        <p class="text-lg font-bold dark:text-red-400 mt-5">Register</p>
        <form action="{%url 'dashboard:register'%}" method="post" class="flex flex-col gap-2">
            {{ form.non_field_errors }}
            {%csrf_token%}
        <div><input autofocus type="text" name="username" placeholder="Username" class="rounded-lg"></div>
        <div><input type="text" name="email" placeholder="Email" class="rounded-lg"></div>
        <div class="flex"><input type="password" name="password" placeholder="Password" class="rounded-lg"></div>
        <div class="flex"><input type="password" name="confirmation" placeholder="Confirm Password" class="rounded-lg"></div>

        <input type="submit", value="Register" class="btn btn-red flex  mx-auto">
        </form>
    </div>

</div>
{% endblock body %}

Keymdall/dashboard/templates/dashboard/userpage.html
{% extends "theme/base.html" %}
{% load static %}

{% block title %} {{user | capfirst}}{% endblock title %}

{% block body %}

<div class="flex flex-col w-screen md:w-full px-8 scrollable overflow-y-auto h-5/6 md:h-fit">
    <div class="flex justify-center items-center ">
        <p class="text-4xl text-teal-500">Hello: <span class="text-teal-700">{{request.user |capfirst}}</span></p>
    </div>

    {% if not user.pin %}
    <div class="flex flex-col bg-yellow-200 rounded-lg w-2/4 mx-auto mt-3 p-2 justify-center">
        <p class="text-yellow-800 font-bold">Remember to set a PIN to enable content Protection</p>

        <button id="set_pin" class="btn btn-yellow mx-auto">Set PIN</li>

    </div>

    {%endif%}



    <div class="flex flex-col md:flex-row w-full my-10 ">

        <sidebar class="flex flex-col flex-shrink items-center
        bg-teal-50 border border-teal-400
        dark:bg-neutral-800
        rounded-t-lg md:rounded-tr-none
        md:rounded-tl-lg md:rounded-bl-lg">

                <p class="flex w-full justify-center font-bold mx-auto py-2
                 bg-teal-100 text-teal-900 dark:bg-opacity-40 dark:text-white">Settings</p>



                <ul class="flex flex-col gap-2 p-2">
                    <li id="update_password" class="btn btn-violet">Change Password</li>
                    <li id="change_email" class="btn btn-green">Change email</li>
                   {% if user.pin %}
                   <li id="update_pin" class="btn btn-yellow">Change PIN</li>


                   {%endif%}
                </ul>


                <button id="delete_account" class="btn btn-red mt-auto mb-5 mx-2">Delete Account</button>

        </sidebar>
        <div class=" flex flex-col flex-grow
        justify-center items-center p-3
        bg-teal-50 border border-teal-300
        dark:bg-neutral-700
        border-t-0 md:border-t rounded-b-lg md:rounded-bl-none
        md:border-l-0 md:rounded-tr-lg md:rounded-br-lg">

            <div class="flex flex-col items-center">
                <p class="italic text-lg border-b border-teal-600 dark:text-white">{{user.email}}</p>
                <p class="text-small text-teal-600">Email</p>
            </div>
            <div class="flex flex-col justify-center items-center
                    p-4 m-2 md:m-6 w-full md:w-1/2 rounded-lg
                    bg-teal-200 border-2 border-teal-300
                    dark:bg-opacity-20">
                    <p>Number of logins:</p>
                    <p class="text-5xl ">{{user.num_logins}}</p>
            </div>


            <div id="folder-section" class="flex flex-col justify-center items-center
                                            p-4 m-2 md:m-6 w-full md:w-1/2
                                            bg-teal-200 dark:bg-opacity-20 border-2 border-teal-300 rounded-lg">

                <div class="text-xl"><span>Folders: </span> <span class="font-bold">{{user.num_folders}} </span></div>

                <div class="flex flex-wrap gap-2 my-8">
                   {% for folder in folders %}

                   <a href="{% url 'vault:index'%}?folder={{folder}}" class="btn btn-{{folder.color}} p-1 rounded-lg">{{folder}}</a>


                   {%endfor%}
                </div>
            </div>

            <div class="self-end">
                <span class="font-bold mr-2">Last access: </span>
                <!-- django date & time template formatting (this example: "3rd, Dec 2022, 10:12 a.m." ) -->
                <span class="border-b-2 border-teal-600 dark:text-teal-400">{{user.last_login |date:"jS, M Y, h:m a"}}</span>
            </div>
        </div>
    </div>
</div>




<div id="modals" class="">
    {%include 'dashboard/dashboard_modals.html'%}
</div>

{% endblock body %}